version: '3.2'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  api:
    build: .
    restart: on-failure
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_URL: db:5432
    ports:
      - "5000:5000"
    depends_on: 
      - db
